# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # ------------- Tests ----------------
      # - name: test and16
      #   run: |
      #     pytest hw/test_components.py -k and16

      # - name: test or8way
      #   run: |
      #     pytest hw/test_components.py -k or8way

      # - name: test mux2way
      #   run: |
      #     pytest hw/test_components.py -k test_mux2way

      # - name: test mux4way
      #   run: |
      #     pytest hw/test_components.py -k test_mux4way

      # - name: test mux8way
      #   run: |
      #     pytest hw/test_components.py -k test_mux8way

      # - name: test deMux8way
      #   run: |
      #     pytest hw/test_components.py -k test_deMux8way

      # - name: test orNway
      #   run: |
      #     pytest hw/test_components.py -k orNway
      
      # - name: test barrelShifter
      #   run: |
      #     pytest hw/test_components.py -k barrelShifter

      # - name: test deMux2way
      #   run: |
      #     pytest hw/test_components.py -k test_deMux2way

      # - name: test deMux4way
      #   run: |
      #     pytest hw/test_components.py -k test_deMux4way

      # - name: test bin2bcd
      #   run: |
      #     pytest hw/test_components.py -k bin2bcd
          
      # - name: Combinacional
      #   run: |
      #     pytest hw/test_components.py
      
      # - name: test add
      #   run: |
      #     pytest hw/test_ula.py -k test_add
      
      # - name: test zerador
      #   run: |
      #     pytest hw/test_ula.py -k test_zerador

      # - name: test inversor
      #   run: |
      #     pytest hw/test_ula.py -k test_inversor
      
      # - name: test addcla4
      #   run: |
      #     pytest hw/test_ula.py -k test_addcla4

      # - name: test bcdAdder
      #   run: |
      #     pytest hw/test_ula.py -k test_bcdAdder
      
      # - name: test binaryDigit
      #   run: |
      #     pytest hw/test_seq.py -k test_binaryDigit

      # - name: test register8
      #   run: |
      #     pytest hw/test_seq.py -k test_register8

      # - name: test registerN
      #   run: |
      #     pytest hw/test_seq.py -k test_registerN
      
      # - name: test pc
      #   run: |
      #     pytest hw/test_seq.py -k test_pc

      # - name: test ram
      #   run: |
      #     pytest hw/test_seq.py -k test_ram

      # - name: test advanced
      #   run: |
      #     pytest sw/assembler/test_asmparser.py -k test_advanced

      # - name: test symbol
      #   run: |
      #     pytest sw/assembler/test_asmparser.py -k test_symbol

      # - name: test labol
      #   run: |
      #     pytest sw/assembler/test_asmparser.py -k test_labol

      # - name: commandType
      #   run: |
      #     pytest sw/assembler/test_asmparser.py -k test_commandType

    - name: test writeArithmetic
        run: |
          pytest sw/vmtranslator test_code_arithmetic

    # pop

    - name: test pop_local
        run: |
          pytest sw/vmtranslator/test_code_pop.py -k test_pop_local

    - name: test pop_this
      run: |
        pytest sw/vmtranslator/test_code_pop.py -k test_pop_this

    - name: test pop_that
      run: |
        pytest sw/vmtranslator/test_code_pop.py -k test_pop_that
        
    - name: test pop_pointer
      run: |
        pytest sw/vmtranslator/test_code_pop.py -k test_pop_pointer

    - name: test pop_temp
      run: |
        pytest sw/vmtranslator/test_code_pop.py -k test_pop_temp
    
    # push

    - name: test push_constant
      run: |
        pytest sw/vmtranslator/test_code_push.py -k test_push_constant

    - name: test push_local
      run: |
        pytest sw/vmtranslator/test_code_push.py -k test_push_local
    
    - name: test push_argument
      run: |
        pytest sw/vmtranslator/test_code_push.py -k test_push_argument
    
    - name: test push_this
      run: |
        pytest sw/vmtranslator/test_code_push.py -k test_push_this

    - name: test push_that
      run: |
        pytest sw/vmtranslator/test_code_push.py -k test_push_that

    - name: test push_temp
      run: |
        pytest sw/vmtranslator/test_code_push.py -k test_push_temp

    - name: test push_pointer
      run: |
        pytest sw/vmtranslator/test_code_push.py -k test_push_pointer

    - name: test code_goto
      run: |
        pytest sw/vmtranslator test_code_goto